spring.application.name=BE

# ? DB CONFIG (QUAN TR?NG)
spring.datasource.url=jdbc:mysql://localhost:3306/mobile_phone
spring.datasource.username=root
spring.datasource.password=123456

# ? JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# server
server.port=8080

# cloudinary
cloudinary.cloud-name=dyev1hklj
cloudinary.api-key=146658122681598
cloudinary.api-secret=wk5wkb6Owji9sirzyCXreolY9j0